services:

  foxglove-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foxglove-bridge
    ports:
      - "7447:7447/tcp"
      - "7447:7447/udp"
      - "8765:8765"
    volumes:
      - ./config/zenoh_router.json5:/config/zenoh_router.json5:ro
      - ./config/zenoh_session.json5:/config/zenoh_session.json5:ro
    environment:
      - ZENOH_ROUTER_CONFIG_URI=/config/zenoh_router.json5
      - RMW_ZENOH_SESSION_CONFIG_URI=/config/zenoh_session.json5
    command: >
      ros2 launch foxglove_bridge foxglove_bridge_launch.xml
      address:=0.0.0.0
      port:=8765
    restart: unless-stopped
